name: "이슈 생성"
description: "이슈 추가 템플릿"
title: "[이슈 종류]: [이슈 제목]"

body:
  - type: input
    id: parentKey
    attributes:
      label: '상위 티켓 번호'
      description: '상위 티켓 번호를 기입해주세요'
      placeholder: 'SLOTIC-00'
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: '📌 이슈 내용 설명'
      description: '이슈에 대해서 간략히 설명해주세요'
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: '✅ TODO'
      description: '이슈에 대한 TODO를 기입해주세요'
      value: |
        - About Details
    validations:
      required: false
